project:
  type: website
  output-dir: docs

website:
  title: "Emma Grace Getz"
  navbar:
    background: "#9e1c57"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: portfolio.qmd
        text: Portfolio
        
format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: false
