project:
  type: website
  output-dir: docs

website:
  title: "Emma Grace Getz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects