project:
  type: website

website:
  title: "Emma Getz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me\
      - text: Portfolio
        href: portfolio.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

publish:
  github-pages:
    branch: gh-pages
